name: BasicCMD
main: BasicCMD\Main
api: [3.0.0-ALPHA12, 3.0.0, 3.0.1, 3.0.2, 4.0.0]
version: 1.0
author: Shabzz102

commands:
  test:
    description: "Use Test Command"
    permission: use.test

  heal:
    description: "Use heal Command"
    permission: use.heal

  feed:
    description: "Use feed Command"
    permission: use.feed

  clear:
    description: "Use clear Command"
    permission: use.clear
